
package projetodesafiojava;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiago
 */
public class JfPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JfPrincipal
     */
    public JfPrincipal() {
      initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jrNaoSeAplica.setSelected(true);
        lista = new ArrayList<>();

    }
    
    public static boolean veiculoCriado = false;
    public ArrayList<Veiculo> lista;
   
    public ArrayList<Veiculo> adicionaVeiculos(Veiculo veiculo){
               
        lista.add(veiculo);
        
        return lista;
        
    }
    
    
    public TipoVeiculo TipoVeiculo(){
        
            TipoVeiculo tv = null;
            
            switch(jcTipo.getSelectedIndex()){
                
                case 0 : tv = TipoVeiculo.CARRO;
                         break;
                case 1 : tv = TipoVeiculo.MOTO;
                         break;
                case 2 : tv = TipoVeiculo.CAMINHAO;
                         break;                                             
            }
        
            return tv;
    }
    
    
    public String VerificaCoresMarcados(){
        
        StringBuilder sb = new StringBuilder();
        String cor;
        
        if( jcBranco.isSelected() ){
            sb.append(jcBranco.getText()).append(",");
        }
        if( jcPreto.isSelected() ){
            sb.append(jcPreto.getText()).append(",");
        }
        if( jcPrata.isSelected() ){
            sb.append(jcPrata.getText()).append(",");
        }
        if( jcAmarelo.isSelected() ){
            sb.append(jcAmarelo.getText()).append(",");
        }
        if( jcVermelho.isSelected() ){
            sb.append(jcVermelho.getText()).append(",");
        }
        if( jcAzul.isSelected() ){
            sb.append(jcAzul.getText()).append(",");
        }
        if( jcVerde.isSelected() ){
            sb.append(jcVerde.getText()).append(",");
        }        
         
       int tamanho = sb.length();
       
       if(tamanho==0){
           cor = "";
       }else{
       cor = sb.substring(0,tamanho-1);
       }
                                             
        return cor;
    }
    
    public String VerificaModeloMarcado(){
        
        String modeloMarcado;
        
        if(jrNaoSeAplica.isSelected()){
            modeloMarcado = jrNaoSeAplica.getText();
        }else
        if(jrManual.isSelected()){
            modeloMarcado = jrManual.getText();
        }else{
            modeloMarcado = jrAutomatico.getText();
        }    
        
        return modeloMarcado;
    }
    
    
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jcTipo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jrAutomatico = new javax.swing.JRadioButton();
        jrManual = new javax.swing.JRadioButton();
        jrNaoSeAplica = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcBranco = new javax.swing.JCheckBox();
        jcPreto = new javax.swing.JCheckBox();
        jcPrata = new javax.swing.JCheckBox();
        jcAmarelo = new javax.swing.JCheckBox();
        jcVermelho = new javax.swing.JCheckBox();
        jcAzul = new javax.swing.JCheckBox();
        jcVerde = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMemo = new javax.swing.JTextArea();
        jbCriarVeiculo = new javax.swing.JButton();
        jbAcelerar = new javax.swing.JButton();
        jbFrear = new javax.swing.JButton();
        jbEstacionar = new javax.swing.JButton();
        jbListarTodosVeiculosCriados = new javax.swing.JButton();

        jButton5.setText("jButton5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Modelo");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Tipo");

        jtfNome.setName(""); // NOI18N

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carro", "Moto", "Caminhão" }));
        jcTipo.setSelectedItem(null);
        jcTipo.setToolTipText("");
        jcTipo.setName(""); // NOI18N
        jcTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcTipoMouseClicked(evt);
            }
        });
        jcTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(jrAutomatico);
        jrAutomatico.setText("Automático");
        jrAutomatico.setEnabled(false);
        jrAutomatico.setName(""); // NOI18N

        buttonGroup1.add(jrManual);
        jrManual.setSelected(true);
        jrManual.setText("Manual");
        jrManual.setEnabled(false);
        jrManual.setName(""); // NOI18N

        buttonGroup1.add(jrNaoSeAplica);
        jrNaoSeAplica.setText("Não se aplica");
        jrNaoSeAplica.setEnabled(false);
        jrNaoSeAplica.setName(""); // NOI18N
        jrNaoSeAplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrNaoSeAplicaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Câmbio");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrAutomatico)
                    .addComponent(jrNaoSeAplica)
                    .addComponent(jrManual))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jrNaoSeAplica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrManual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrAutomatico)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jcBranco.setText("Branco");
        jcBranco.setToolTipText("");
        jcBranco.setName(""); // NOI18N

        jcPreto.setText("Preto");
        jcPreto.setName(""); // NOI18N

        jcPrata.setText("Prata");
        jcPrata.setName(""); // NOI18N

        jcAmarelo.setText("Amarelo");
        jcAmarelo.setName(""); // NOI18N

        jcVermelho.setText("Vermelho");
        jcVermelho.setName(""); // NOI18N

        jcAzul.setText("Azul");
        jcAzul.setName(""); // NOI18N

        jcVerde.setText("Verde");
        jcVerde.setName(""); // NOI18N
        jcVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcVerdeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Cores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcBranco)
                    .addComponent(jcPreto)
                    .addComponent(jcPrata)
                    .addComponent(jcAmarelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcVermelho)
                    .addComponent(jcAzul)
                    .addComponent(jcVerde))
                .addGap(37, 37, 37))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcBranco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcPreto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcPrata)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcAmarelo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jcVermelho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcAzul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcVerde)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jtMemo.setColumns(20);
        jtMemo.setRows(5);
        jtMemo.setName("mmLog"); // NOI18N
        jScrollPane1.setViewportView(jtMemo);

        jbCriarVeiculo.setText("Criar Veículo");
        jbCriarVeiculo.setName(""); // NOI18N
        jbCriarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCriarVeiculoActionPerformed(evt);
            }
        });

        jbAcelerar.setText("Acelerar");
        jbAcelerar.setName(""); // NOI18N
        jbAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAcelerarActionPerformed(evt);
            }
        });

        jbFrear.setText("Frear");
        jbFrear.setName(""); // NOI18N
        jbFrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFrearActionPerformed(evt);
            }
        });

        jbEstacionar.setText("Estacionar");
        jbEstacionar.setName(""); // NOI18N
        jbEstacionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEstacionarActionPerformed(evt);
            }
        });

        jbListarTodosVeiculosCriados.setText("Listar todos veículos criados");
        jbListarTodosVeiculosCriados.setName(""); // NOI18N
        jbListarTodosVeiculosCriados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListarTodosVeiculosCriadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jbCriarVeiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAcelerar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbFrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbEstacionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbListarTodosVeiculosCriados, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(jbCriarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbFrear, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbEstacionar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbListarTodosVeiculosCriados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrNaoSeAplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrNaoSeAplicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrNaoSeAplicaActionPerformed

    private void jbCriarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCriarVeiculoActionPerformed
        
        if(jtfNome.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Modelo não informado. Verifique!");
            jtfNome.grabFocus();
        }else
        if (jcTipo.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(null, "Tipo de veículo não informado. Verifique!");
            jtfNome.grabFocus();
        }else{
        veiculoCriado = true;               
        jtMemo.setText("");
        TipoVeiculo tpVeiculo = TipoVeiculo();
        Veiculo v = new Veiculo(jtfNome.getText(), tpVeiculo, VerificaModeloMarcado(), VerificaCoresMarcados());        
        adicionaVeiculos(v);
        jtMemo.append(v.toString());
        }                

    }//GEN-LAST:event_jbCriarVeiculoActionPerformed

    private void jbAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAcelerarActionPerformed
       if(veiculoCriado)    {
        jtMemo.append(Veiculo.acelerar());
       }else{
           JOptionPane.showMessageDialog(null, "Veículo não foi criado!");
       }     
       
    }//GEN-LAST:event_jbAcelerarActionPerformed

    private void jbFrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFrearActionPerformed
       if(veiculoCriado)    {
        jtMemo.append(Veiculo.frear());
       }else{
           JOptionPane.showMessageDialog(null, "Veículo não foi criado!");
       }            
    }//GEN-LAST:event_jbFrearActionPerformed

    private void jbEstacionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEstacionarActionPerformed
       if(veiculoCriado)    {
        Veiculo.estacionar(jtMemo);
       }else{
           JOptionPane.showMessageDialog(null, "Veículo não foi criado!");
       }
    }//GEN-LAST:event_jbEstacionarActionPerformed

    private void jcTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcTipoMouseClicked
        
    }//GEN-LAST:event_jcTipoMouseClicked

    private void jcTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoActionPerformed
      
        if (jcTipo.getSelectedIndex()==0){
            jrNaoSeAplica.setEnabled(true);
            jrManual.setEnabled(true);
            jrAutomatico.setEnabled(true);
        }else{
            jrNaoSeAplica.setSelected(true);
            jrNaoSeAplica.setEnabled(false);
            jrManual.setEnabled(false);
            jrAutomatico.setEnabled(false);
        }
    }//GEN-LAST:event_jcTipoActionPerformed

    private void jbListarTodosVeiculosCriadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListarTodosVeiculosCriadosActionPerformed
        jtMemo.setText("");
        jtMemo.append(Veiculo.listaVeiculos(lista).toString());            
    }//GEN-LAST:event_jbListarTodosVeiculosCriadosActionPerformed

    private void jcVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcVerdeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JfPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAcelerar;
    private javax.swing.JButton jbCriarVeiculo;
    private javax.swing.JButton jbEstacionar;
    private javax.swing.JButton jbFrear;
    private javax.swing.JButton jbListarTodosVeiculosCriados;
    private javax.swing.JCheckBox jcAmarelo;
    private javax.swing.JCheckBox jcAzul;
    private javax.swing.JCheckBox jcBranco;
    private javax.swing.JCheckBox jcPrata;
    private javax.swing.JCheckBox jcPreto;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JCheckBox jcVerde;
    private javax.swing.JCheckBox jcVermelho;
    private javax.swing.JRadioButton jrAutomatico;
    private javax.swing.JRadioButton jrManual;
    private javax.swing.JRadioButton jrNaoSeAplica;
    private javax.swing.JTextArea jtMemo;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
